name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Step 2: Debug Token Substitution
      - name: Debug Token Substitution
        run: |
          echo "Token substitution test: ${HF_TOKEN:0:5}... (truncated for security)"
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      # Step 3: Test Network Connectivity
      - name: Test Network Connectivity
        run: |
          ping -c 4 huggingface.co

      # Step 4: Push to Hugging Face Hub
      - name: Push to Hugging Face Hub
        run: |
          git remote set-url origin https://huggingface.co/spaces/Tanishq0505/Search_Engine_llm
          git remote -v
          git push --force https://$HF_TOKEN@huggingface.co/spaces/Tanishq0505/Search_Engine_llm main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
