name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Step 2: Debug Token Substitution and Branch
      - name: Debug Token and Branch
        run: |
          echo "Token: ${{ secrets.HF_TOKEN }}"
          git branch
          git remote -v
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      # Step 3: Push to Hugging Face Hub
      - name: Push to Hugging Face Hub
        run: |
          git remote set-url origin https://huggingface.co/spaces/Tanishq0505/Search_Engine_llm
          echo "Verifying remote configuration:"
          git remote -v
          echo "Pushing changes to Hugging Face Hub..."
          git push --force https://${HF_TOKEN}@huggingface.co/spaces/Tanishq0505/Search_Engine_llm main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
